# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow      
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        set -xe
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install paconn
        mkdir -p ~/.paconn
        echo $AZURE_TOKEN > ~/.paconn/accessTokens.json
        cp act.txt ~/.paconn/accessTokens.json
        cat ~/.paconn/accessTokens.json
        ls ~/.paconn/
        pwd
        ls ~/
        paconn login
        cd dist
        paconn update -s settings.json

